### PR TITLE
Update seed.rb

### PR DESCRIPTION
**Pull request by bfpepper**
Add functionality to pull mentors for seed from census database.

### CODE REVIEW

**Comment by neight-allen** [comment]
1. Your PR doesn't describe what's been done
2. Your PR includes a lot of other work from another branch
3. You should be using an ENV variable for the access token, as I mentioned on the card in Tracker.

**Comment by bfpepper** [comment]
@neight-allen Right now we just create the PR. I'll ping you when its 100%

**Comment by vidoseaver** [comment]
This now passes.

**Comment by vidoseaver** [comment]
Added travis ci env code. It now passes.

**Pull request merged**
