### PR TITLE
Db update

### PR DESCRIPTION
**Pull request by bfpepper**
@neight-allen This closes out card #139246683 for updating the DB per our discussion.

### CODE REVIEW

**Comment by neight-allen** [comment]
There's a lot more in this PR than just that card. Could you list all the cards that are affected, and any changes you made outside of cards.

**Comment by neight-allen** [comment]
Do you know which commits are relevant to oAuth? Is it only `29c49b2`?

**Comment by bfpepper** [comment]
@neight-allen  commits ff86d3c, ce719a2, 83ffef6, 14f1bfd, 8fdeefe, are all ones that deal with the DB reconfigure. OAuth was dealt with in the OAuth 2 PR.

**Comment by neight-allen** [comment]
So we're done with this right?

**Comment by bfpepper** [comment]
@neight I believe so. My suspicion is that these changes (any worth keeping) have already been implemented by other PRs. can probably delete this PR.

**Pull request closed without merging**
